### ISSUE TITLE
Issues on Big Sur M1 Mac

### ISSUE THREAD

**Issue by robertritz** [amgaa/mongolian-phonetic#2]
I'm having an issue with several keys that require special characters on Big Sur with an M1 Mac. Combinations such as ch -> ч or sh -> ш are working fine. 

However :: -> ь and ;; -> ъ are not working. Also, i: -> й is not working. 

This isn't the first keyboard shortcut issue I've had on Big Sur, so I believe it may be some changes on the M1 in Big Sur that are causing this. Or perhaps I'm doing something wrong?

**Comment by amgaa** [comment]
Hello there! Thank you for your interest in this keyboard layout. My apologies for the delayed response. I have updated the layout and tested it out with my M2 MacBook, and it seems to be working fine. 

I wanted to let you know that the key mappings for the characters ь and ъ have both been changed. When I was developing this layout, I was using a Japanese keyboard and was not aware that the position of the : and ; keys could be inconvenient. Therefore, I changed the mappings to ' and " instead.
